name: Deploy Backend to DigitalOcean Droplet

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: |
          cd backend
          ./gradlew clean build -x test

      - name: Prepare Deployment Package
        run: |
          mkdir deployment_package
          cp backend/build/libs/application.jar deployment_package/application.jar
          cp -r backend/DockerImages deployment_package/DockerImages

      - name: Archive Deployment Package
        run: tar -czvf deployment_package.tar.gz deployment_package

      - name: Copy Deployment Package to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "deployment_package.tar.gz"
          target: "/tmp"

      - name: Deploy on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            tar -xzvf /tmp/deployment_package.tar.gz -C /tmp
            PID=$(lsof -ti:8080) || true
            if [ ! -z "$PID" ]; then
            kill $PID || true
            fi
            cd /tmp/deployment_package
            nohup java -jar application.jar > app.log 2>&1 &
            exit 0
